TM_ARTIST = "https://app.ticketmaster.com/discovery/v2/attractions.json?classificationName=Music"
TM_VENUE = "https://app.ticketmaster.com/discovery/v2/venues.json?classificationName=Music&countryCode=us"
TM_EVENT = "https://app.ticketmaster.com/discovery/v2/events.json?classificationName=Music&countryCode=us&sort=date,asc&attractionId="
TM_EVENT_2 = "https://app.ticketmaster.com/discovery/v2/events.json?classificationName=Music&sort=date,asc"
OW_API = "https://openweathermap.org/data/2.5/weather?units=imperial"
NEW_VEN = "http://app.ticketmaster.com/discovery/v2/venues/"
