TMART = "https://app.ticketmaster.com/discovery/v2/attractions.json?classificationName=Music"
TMVEN = "https://app.ticketmaster.com/discovery/v2/venues.json?"
TMEVENT = "https://app.ticketmaster.com/discovery/v2/events.json?classificationName=Music&sort=date,asc&attractionId="
TMEVENT2 = "https://app.ticketmaster.com/discovery/v2/events.json?classificationName=Music&sort=date,asc"
OWAPI = "https://openweathermap.org/data/2.5/weather?units=imperial&lat=70.2&lon=139&appid="
