# Generated by Django 2.2.4 on 2019-08-21 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('artistId', models.CharField(max_length=255, unique=True)),
                ('genre', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueLoc', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 21, 11, 57, 0, 68561, tzinfo=utc))),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueName', models.CharField(max_length=255)),
                ('VenueId', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('Event', models.ManyToManyField(to='weather.Event')),
            ],
        ),
    ]
