# Generated by Django 2.2.4 on 2019-08-18 23:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 18, 23, 32, 0, 319735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='performer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.Artist'),
        ),
    ]
