# Generated by Django 2.2.4 on 2019-08-19 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190818_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 19, 0, 39, 0, 28543, tzinfo=utc)),
        ),
    ]
