# Generated by Django 2.2.4 on 2019-08-21 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190821_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 12, 1, 33, 482730, tzinfo=utc)),
        ),
    ]
