# Generated by Django 2.2.4 on 2019-08-20 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20190819_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artistId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 3, 27, 23, 811221, tzinfo=utc)),
        ),
    ]
