# Generated by Django 2.2.4 on 2019-08-21 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20190821_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 13, 29, 39, 873379, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='venue',
            name='VenueId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
