# Generated by Django 2.2.4 on 2019-08-21 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20190821_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 14, 34, 25, 595220, tzinfo=utc)),
        ),
    ]
