# Generated by Django 2.2.4 on 2019-08-22 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20190821_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 11, 20, 39, 978342, tzinfo=utc)),
        ),
    ]
