# Generated by Django 2.2.4 on 2019-08-23 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_auto_20190823_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 11, 18, 55, 749252, tzinfo=utc)),
        ),
    ]
