# Generated by Django 2.2.4 on 2019-08-23 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_auto_20190823_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='eventId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 11, 43, 9, 474047, tzinfo=utc)),
        ),
    ]
