# Generated by Django 2.2.4 on 2019-09-02 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0020_auto_20190902_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 7, 11, 44, 959380, tzinfo=utc)),
        ),
    ]
